modules/whisper_Inference.py

Add the feature to remove input file(s) (Upload files, youtube audio file, mic file) when finished.
I add the `try-except-finally` block in `transcribe` handlers from `WhisperInference`.

Add to remove input file(s) when finished

---

modules/base_interface.py
modules/nllb_inference.py
modules/whisper_Inference.py

Add code to release cuda cache when finished job.
This modified code may be able to mitigate 'CUDA Out of memory error' in case of running t2t translation after creating subtitle file(s).

Mitigate CUDA OutOfMemory error

---

app.py
notebook/whisper-webui.ipynb

add notebook for running webui

add notebook

---

app.py
requirements.txt

To fix 
- #23 
upgraded gradio to 3.37.0

upgraded gradio version to 3.37.0

---

app.py
modules/nllb_inference.py
modules/whisper_Inference.py

added checkbox whether to add timestamp at the end of the filename

---

app.py
modules/subtitle_manager.py
modules/whisper_Inference.py

This adds a simple txt format on top of the subtitles formats supported

Adding txt support

---

modules/faster_whisper_inference.py
modules/whisper_Inference.py

beam_size` 1 for both models. This will be a tunable parameter soon.

set default beam size for both models

---

app.py
modules/faster_whisper_inference.py
modules/whisper_Inference.py

added
- beam_size
- log_prob_threshold
- no_speech_threshold

add advanced parameter tab

---

app.py
modules/faster_whisper_inference.py
modules/whisper_Inference.py

fix compute type error

---

app.py
modules/faster_whisper_inference.py
modules/whisper_Inference.py

add compute_type dropdown

---

modules/faster_whisper_inference.py

To fix #40
To better display `compute_types` by device

better display of available compute types

---

app.py
modules/faster_whisper_inference.py
modules/subtitle_manager.py
modules/whisper_Inference.py

Add "txt" file format option

---

modules/subtitle_manager.py

patch file name

---

requirements.txt

version fix for faster-whisper

---

.dockerignore
Dockerfile
README.md

resolve #120 
It runs perfectly on my test environment(Docker Desktop + wsl2). You can test it by build locally(see README) or use the image built by action in my repo.
```
docker pull ghcr.io/koro33/whisper-webui:master
```

feat: add docker support

---

requirements.txt

To resolve #123,
fixed wrong pytorch version

fix torch version

---

.github/workflows/shell-scrpit-test.yml
Install.sh
start-webui.sh

Add shell script

---

modules/faster_whisper_inference.py
requirements.txt

The issue #144 still persists in faster-whisper 1.0.2 .
So I didn't revert #145, but only upgrade faster-whisper to 1.0.2

upgrade faster-whipser to 1.0.2

---

app.py
requirements.txt

- related issue
- #146
Tested and confirmed it works fine.

Upgrade gradio version

---

app.py
modules/faster_whisper_inference.py
modules/whisper_Inference.py
modules/whisper_parameter.py

added `nb_compression_ratio_threshold`
- Related Issue
- #130

add params

---

app.py
modules/faster_whisper_inference.py
modules/whisper_parameter.py

To resolve whisper hallucination
- Related issue
- #152 
This Silero VAD is only possible in faster-whisper

add `vad_filter`

---

.github/workflows/publish-docker.yml

added action for docker hub push

add docker hub publish action

---

app.py

Related Issue:
- #152 
According to [comment1](https://github.com/jhj0517/Whisper-WebUI/issues/152#issuecomment-2123817314), [comment2](https://github.com/jhj0517/Whisper-WebUI/issues/152#issuecomment-2137085991), and some research, 
`large-v2`  gives better results than `large-v3`. 
So change the default model from `large-v3` to `large-v2`.

update default model to `large-v2`

---

app.py
modules/faster_whisper_inference.py
modules/whisper_parameter.py

Related Issues
- #158 
1. added Silero VAD Options tab in the WebUI
2. added `vad_options` in faster-whisper inference

Add Silero VAD Options parameter

---

app.py

Related issue
- #160 
1. Added `inbrowser` to `launch()` arg

add launch arg

---

notebook/whisper-webui.ipynb
requirements_colab.txt

Related Issues :
- #162
Changed : 
1.  upgraded faster whisper to 1.0.2
2.  removed requirements_colab.txt

fix colab version conflicts

---

modules/faster_whisper_inference.py

- #164 
Changed:
1. Enabled locally load model path for faster-whisper

Enable fine-tuned faster whisper model

---

modules/faster_whisper_inference.py

- #166
- #164 
Changed:
1. Fixed path bug

Fix path bug

---

modules/faster_whisper_inference.py
modules/whisper_Inference.py
start-webui.sh

- #169
Changed:
1. removed deactivate line
2. add `device = "mps"` line for Mac

Fix compatibility with Mac

---

app.py

essential when reverse proxying Gradio on a url+prefix

add root_path argument

---

app.py
modules/deepl_api.py
modules/faster_whisper_inference.py
modules/insanely_fast_whisper_inference.py
modules/nllb_inference.py
modules/translation_base.py
modules/whisper_Inference.py
modules/whisper_base.py

Changed:
1. Added `--output_dir` cli arg
2. Added `--nllb_model_dir` cli arg
3. Fixed NLLB translation model bug
4. Fixed `--whisper_type` arg hint

Add output dir arg

---

modules/diarize/diarizer.py

- https://github.com/jhj0517/Whisper-WebUI/issues/168#issuecomment-2192892298
Changed:
1. Fixed strip bug

Fix strip bug

---

app.py
modules/vad/silero_vad.py
modules/whisper/faster_whisper_inference.py
modules/whisper/insanely_fast_whisper_inference.py
modules/whisper/whisper_Inference.py
modules/whisper/whisper_base.py

Changed:
1. Modularized VAD for integration with any type of whisper inferencer

Modularize VAD

---

notebook/whisper-webui.ipynb

- #185 
Changed:
1. Added pyannote.audio

Fix colab requirements

---

notebook/whisper-webui.ipynb

Changed:
1. Update `--whisper_type` arg to dropdown

Update colab 

---

app.py
modules/translation/nllb_inference.py
modules/translation/translation_base.py

- #189 
Changed:
1. Added `max_length` parameter
2. Fixed output path for NLLB translation to `outputs\translations`
3. Removed input file removing logic after the translation

Add `max_length` parameter

---

app.py
modules/utils/files_manager.py
modules/whisper/whisper_base.py

- #193
- #38 
1. Added "Input Folder Path (Optional)" tab ( only shown if `--colab` arg is used )
2. Added file util functions

Add local input folder path

---

app.py
modules/whisper/faster_whisper_inference.py
modules/whisper/whisper_parameter.py

- #199 
1. Added all parameters from faster-whisper
2. Refactor whisper parameters in gradio app into the function to reduce repetitiveness

Add all faster-whisper parameter

---

app.py

1. Fixed translations output path

Fix translation output path

---

notebook/whisper-webui.ipynb

- #203 
1. Used forked branch of pytube
2. Update some requirements

fix pytube bug and update some requirements

---

app.py

1. Added info parameter for VAD

Added info to the VAD parameter

---

modules/diarize/audio_loader.py
modules/diarize/diarizer.py

- https://github.com/jhj0517/Whisper-WebUI/pull/206#issuecomment-2224577438
1. Fixed type hint in diarization function
2. Update `load_audio()` to pre-process `np.ndarray` also

Fix type hint in diarization function

---

modules/translation/deepl_api.py

Output files are not all listed after finishing translation
1. Fixed bug

Add output path

---

app.py
modules/diarize/audio_loader.py
modules/diarize/diarize_pipeline.py
modules/vad/silero_vad.py
modules/whisper/faster_whisper_inference.py
modules/whisper/whisper_base.py

- #212 
1. Revert `silence_non_speech`
2. Limit VAD feature to faster-whisper only
3. Fixed wrong default beam size value

Limit Vad feature to faster-whisper

---

app.py
modules/vad/silero_vad.py
modules/whisper/faster_whisper_inference.py
modules/whisper/whisper_base.py

- #212 
1. Moved VAD feature to abstract class so I can use it on every whisper implementation

Modularize VAD feature

---

app.py
modules/whisper/whisper_factory.py

1. Refactored to use factory pattern

Refactor to factory pattern

---

app.py

1. Refactoring / Applying cli args

Refactoring args

---

app.py
modules/whisper/faster_whisper_inference.py
modules/whisper/insanely_fast_whisper_inference.py
modules/whisper/whisper_Inference.py
modules/whisper/whisper_base.py
modules/whisper/whisper_factory.py

1. Refactor model_dir args in the whisper implementation classes
2. Fixed that only the faster-whisper model dir was being applied

Refactor args structure

---

modules/utils/youtube_manager.py
notebook/whisper-webui.ipynb
requirements.txt

- #220
1. Update to use [pytubefix](https://github.com/JuanBindez/pytubefix).

Fix pytube bug

---

start-webui.bat

- #226 
1. Fixed the bug that CLI argument was not affecting

Fix the bug that CLI argument was not affecting

---

requirements.txt

- #226 
1. Downgraded `transformers` to 4.42.3
2. Added comment about CUDA distribution of the torch

Downgrade transformers

---

modules/translation/nllb_inference.py

- #229 
1. Add model path check function
2. Add `local_files_only` so that it does not try to connect to the Internet.

Add model path check fucntion and `local_files_only`

---

modules/translation/deepl_api.py
modules/translation/translation_base.py

- #229 
1. Fixed output file paths for translations

Fix output path for translation

---

README.md
docker-compose.yaml

1. Added `docker-compose.yaml` for convenient command

Add docker-compose

---

modules/diarize/diarizer.py
modules/whisper/whisper_base.py

- #168
1. Fixed wrong device reference on Diarizer

Fix device bug

---

notebook/whisper-webui.ipynb

- #256 
1. git+ install pytubefix

Fix pytubefix

---

requirements.txt

- #258 
1. Updated gradio to 4.43.0

Update gradio to 4.43.0

---

app.py
modules/whisper/whisper_base.py

- #263 
1. Added the `add_timestamp` parameter that should be there.

Fix mic bug

---

modules/utils/files_manager.py
modules/uvr/music_separator.py

1. Fix the error when input is the video not audio.

Fix unsupported video format error

---

modules/utils/files_manager.py

- #280 
1. Added some missing video extensions

Add missing video extension

---

docker-compose.yaml

- #279 
1. Removed old `version` attribute

Remove `version` attribute

---

app.py
configs/default_parameters.yaml
modules/uvr/music_separator.py
modules/whisper/whisper_base.py

1. Added dedicated tab for BGM separation
2. Update default `save_files` value to False

Add dedicated bgm separation tab

---

configs/default_parameters.yaml

- #287 
1. Update default VAD parameters to reduce hallucination

Update defaults of the vad

---

modules/whisper/faster_whisper_inference.py
modules/whisper/whisper_parameter.py

1. Fixed wrong dataclass defaults

Fix defaults dataclass value

---

modules/translation/nllb_inference.py
modules/translation/translation_base.py
modules/whisper/faster_whisper_inference.py
modules/whisper/insanely_fast_whisper_inference.py
modules/whisper/whisper_Inference.py
modules/whisper/whisper_base.py

1. Added defaults to the function

Add defaults to functions

---

app.py
configs/default_parameters.yaml
modules/whisper/whisper_parameter.py

1. Added `uvr_enable_offload` parameter

Add UVR model offload boolean value 

---

modules/whisper/whisper_base.py

Add UVR model offload boolean value

---

modules/whisper/insanely_fast_whisper_inference.py

- #301
1. Used limited parameters for English-only models

Use limited parameters for English-only models

---

modules/utils/youtube_manager.py
modules/whisper/whisper_base.py

- #304
1. Reformat corrupted youtube audio file with ffmpeg
2. Add temp file cleaning logic

Fix corrupted youtube audio file

---

app.py

- https://github.com/jhj0517/Whisper-WebUI/issues/152#issuecomment-2387119140
1. Updated label & info for clearer use of submodels.

Add infos for the clear use of submodels

---

app.py

- #311
1. Enabled custom values for compute type

Allow custom values

---

requirements.txt

- #314
1. Removed semi colon that might cause the bug

Remove semi colons

---

.github/workflows/ci-shell.yml
.github/workflows/ci.yml

- #322
1. Added `intel-gpu` branch for CI

Add branch

---

app.py

- #333
1. Updated info about diarization models

Update diarization model instruction

---

notebook/whisper-webui.ipynb

Add gradio-i18n on Colab

---

.github/workflows/ci-shell.yml
.github/workflows/ci.yml
README.md

- #344
1. Add python 3.10 ~ 3.12 to CI
2. Update README about python version

Add python 3.10 ~ 3.12

---

.gitignore
configs/translation.yaml

- Added Ukrainian translations for various UI elements and features.
- Added Russian translations for various UI elements and features.
- Updated .gitignore to include __pycache__ directory.
Add Ukrainian and Russian translations to translation.yaml

feat: add Ukrainian and Russian translations to translation.yaml

---

modules/utils/subtitle_manager.py

- #359
1. Fixed wrong VTT format

Fix subtitle format for WebVTT

---

notebook/whisper-webui.ipynb

1. Update `gradio-i18n` to official one in coalb

Update gradio-i18n to official one in coalb

---

modules/whisper/base_transcription_pipeline.py

- #367
1. Fix language selection bug

Fix language key bug

---

modules/diarize/diarize_pipeline.py
modules/diarize/diarizer.py

- #373
1. Fixed diarization that returned wrong type.
Needs to improve testing so that it actually produces the correct result. Currently it checks if it's returning a `str` type.

Fix diarization 

---

.github/workflows/ci.yml
modules/whisper/base_transcription_pipeline.py
tests/test_config.py
tests/test_transcription.py

- #373
1. Calculate WER between gen result & answer and pass if `WER < 0.1`. And check if the diarization actually works or not as well.

Improve test based on WER

---

modules/utils/subtitle_manager.py

1. Fixed the bug that webvtt is not working in gradio

Fix webvtt format

---

modules/whisper/insanely_fast_whisper_inference.py

- #222
1. Enables fine-tuned models for `insanely_fast_whisper` implementation

Enable fintuned models for `insanely_fast_whisper`

---

notebook/whisper-webui.ipynb

Fix drop down bug

---

app.py

- #383
1. Add ssl related options

Add SSL related options

---

configs/translation.yaml

1. add simplifiled chinese localization

add chinese localization

---

notebook/whisper-webui.ipynb

- #392
1. Fix tokenizers version

Fix tokenizers

---

configs/translation.yaml

Updated translation.yaml (de: Deutsch)

---

configs/translation.yaml

The following PR adds Basque ("eu") translations to translation.yaml
Thanks!!

Add Basque translations to translation.yaml

---

requirements.txt

- #403 
The following PR fixes the issue #403

Update pyannote.audio version to 3.3.2 in requirements.txt (fixes #403)

---

.github/pull_request_template.md
modules/utils/subtitle_manager.py

- #408
There's a unimplemented function error for subtitle writer
1. Fix unimplemented function error

Fix unimplemented error

---

docker-compose.yaml

1. Update docs about directory path mounting

chore: Update docs in docker compose

---

tests/test_vad.py

Testing whole pipeline feels too heavy, added light test that runs only VAD
1. Added the vanilla VAD test

Add vanilla VAD test

---

modules/uvr/music_separator.py

- #424
1. Explicitly says that it will only display 0% until the job is complete.

Update progress message

---

backend/requirements-backend.txt

- https://github.com/jhj0517/Whisper-WebUI/actions/runs/12390562460
Failed to install dependencies
1. Fix relative path

Fix relative path

---

backend/Dockerfile

- https://github.com/jhj0517/Whisper-WebUI/actions/runs/12390978199
1. Fix the requirements does not exist bug

Copy the requirements

---

app.py
notebook/whisper-webui.ipynb

- #129
1. Add google drive path mounting in colab
2. Add `allowed_paths` arg to `launch()` to fix bug

Add Google Drive path mounting on Colab

---

modules/translation/nllb_inference.py

- #442
1. Update the logic that checks if the model actually exists in the path

Fix nllb model path check

---

app.py
configs/translation.yaml
modules/whisper/base_transcription_pipeline.py
modules/whisper/faster_whisper_inference.py
modules/whisper/whisper_Inference.py

- #444
1. Whisper's End-to-End translation feature is available for all model sizes, not just large sizes. So enable it for all model sizes.

Enable Whisper's End-to-End translation feature for models below large sizes.

---

app.py

- #449
1. Fix i18n initialization that occurs when the browser's language code key is not included in the i18n file.

Fix i18n initialization bug

---

app.py
modules/utils/files_manager.py

This change resolves a compatibility issue with iOS file uploads by adding a file_types parameter to gr.Files() as referenced in gradio-app/gradio#10012.

Added file_types parameter for iOS support

---

notebook/whisper-webui.ipynb

- #454
1. Add an example screenshot of how to use the directory path from Google Drive for better understanding

Add example screenshot

---

modules/whisper/base_transcription_pipeline.py

- https://github.com/jhj0517/Whisper-WebUI/issues/456#issuecomment-2592955634
1. Set `origin_audio` after BGM removal

Set `origin_audio` after bgm removal

---

notebook/whisper-webui.ipynb

1. Fixed typos in colab notebook

Fix typos in notebook

---

app.py
modules/whisper/base_transcription_pipeline.py
tests/test_transcription.py

- #464
1. Feature to include subdirectory files

Feature to include subdirectory files

---

modules/whisper/base_transcription_pipeline.py

Fix elapsed time

---

app.py

- #472
1. Added `show_download_button` to the microphone

Add `show_download_button` on microphone

---

requirements.txt

Fix for issue with insanely-fast-whisper
- #470 
1. Fixed version of transformers  to 4.47.1 - 4.48.0 or above will currently create issues.

fixed transformers version for issue #470

---

backend/configs/config.yaml
configs/default_parameters.yaml
configs/translation.yaml
modules/whisper/base_transcription_pipeline.py
modules/whisper/data_classes.py

- after everything is finished the memory consumption is still high 
- #413
- #398
1. add options in the Gradio UI to unload the Whisper and Diarization models analog to the option to unload the BGM model

add option to unload whisper and diarizer model when done

---

modules/whisper/faster_whisper_inference.py
modules/whisper/insanely_fast_whisper_inference.py

- Remove placeholders from model list
1. Remove placeholder files from model list

Exclude placeholders from model list

---

configs/translation.yaml

chore: Update translation

---

modules/diarize/diarizer.py

- #511
1. Fix device error in diarizer

Fix diarizer device

---

app.py
modules/utils/logger.py
modules/whisper/faster_whisper_inference.py
modules/whisper/insanely_fast_whisper_inference.py
modules/whisper/whisper_factory.py

- https://github.com/jhj0517/Whisper-WebUI/issues/507#issuecomment-2707225338
1. `faster-whisper` may not support `xpu` device ( I couldn't find the information about it in `ctranslate2` docs ), 
So use insanely_fast_whisper implementation for `xpu` device.

Switch to insanely_fast_whisper for XPU device

---

modules/uvr/music_separator.py

Add "mps" device

---

docker-compose.yaml

1. Define container name in docker-compose.yaml

Define container name in docker-compose.yaml

---

docker-compose.yaml

- https://github.com/jhj0517/Whisper-WebUI/issues/531#issuecomment-2783725970
1. Update comment about usage with CPU in `docker-compose.yaml`

Update `docker-compose.yaml` about cpu usage

---

app.py

- https://github.com/jhj0517/Whisper-WebUI/issues/327#issuecomment-2802029807
1. Increase maximum file cache age from 1hour to 1day

Increase maximum file cache age

---

docker-compose.yaml

- https://github.com/jhj0517/Whisper-WebUI/issues/250#issuecomment-2837806902
1. Add config files to the docker compose

Add configs to the docker compose

---

requirements.txt

- https://github.com/jhj0517/Whisper-WebUI/issues/568#issuecomment-3121473628
- https://github.com/jhj0517/gradio-i18n/pull/3
1. Use wrapped version of gradio-18n package which fixed encoding issue

fix: i18n encoding issue

---

app.py

1. Hide language setting by default

fix: hide language setting by default

---

configs/translation.yaml

Added Dutch translation in translation.yaml

Add Dutch translation to translation.yaml
