app.py
modules/faster_whisper_inference.py
requirements.txt
user-start-webui.bat

faster-whisper implemented from here
https://github.com/guillaumekln/faster-whisper
- added new command line argument `--disable_faster_whisper`
- I set the default transcribe action from openAI's to faster-whisper
**My personal experience:**
Transcription time of 30 minutes of audio file reduced from 4 minutes 8 seconds -> 3 minutes 53 seconds.
I only transcribed a 30 minutes audio file to compare but it's not much amount of reduction as I expected. 
Probably it's efficient for reducing VRAM usage though.

Implement faster whisper

---

modules/faster_whisper_inference.py
modules/whisper_Inference.py

To resolve 
- #65 
`list[str]` is only valid from Python 3.9
Reference
- https://stackoverflow.com/questions/75202610/typeerror-type-object-is-not-subscriptable-python
- https://docs.python.org/3.9/whatsnew/3.9.html#type-hinting-generics-in-standard-collections

Fix typing errors

---

app.py
user-start-webui.bat

According to the [documentation](https://www.gradio.app/docs/interface#interface-queue-arguments), this allows to requests to be processed directly, skipping the queue.
You can still use the API without this, but it's better to include it as an argument.
- related issue:
- #137

add `api_open`

---

app.py
modules/faster_whisper_inference.py
modules/whisper_Inference.py
user-start-webui.bat

To resolve
- #100 
Tasks:
- added `--faster_whisper_model_dir` arg for faster-whipser model directory path
- added `--whisper_model_dir` arg for whipser model directory path
Example usage:
```
python app.py --faster_whisper_model_dir "C:\Whisper-WebUI\my_faster_whisper_model_path"
```
```
python app.py --whisper_model_dir "C:\Whisper-WebUI\my_whisper_model_path"
```

Enable custom local model path

---

modules/whisper/faster_whisper_inference.py

Related issues:
- #180 
Changed:
1. Use "auto" for mps. Supported devices in faster-whisper are : `("cpu", "cuda", "auto")`.

Fix mac device bug

---

modules/whisper/faster_whisper_inference.py

Related issues:
- #192
Changed:
1. Just set the device to "auto" if not cuda

Fix `get_device()`

---

app.py
modules/vad/silero_vad.py
modules/whisper/whisper_base.py
modules/whisper/whisper_parameter.py
requirements.txt

- #197 
1. Migrate faster-whisper to 1.0.3
2. Removed deprecated parameter `window_size_sample`

Migrate faster whisper to 1.0.3

---

modules/whisper/faster_whisper_inference.py

- #209
1.  Pre process empty Textbox parameters to `None`

set to `None` for empty Textbox values

---

modules/vad/silero_vad.py
modules/whisper/whisper_base.py

- #212
1. Added `silence_non_speech` parameter to VAD processing. When it's `True`, non-speech segments are silenced instead of cutting off.
2. Updated `collect_chunks()` accordingly

Add option to silence non-speech segments in VAD instead of cutting off

---

modules/whisper/whisper_base.py

- #232 
1. Disable `safe_file_name()` on local file

Disable `safe_filename()` on local file

---

modules/whisper/faster_whisper_inference.py

Initial prompt should be included in the transcribe function otherwise the field won't do anything when filled out in the web ui.

Fix missing initial prompt parameter

---

README.md
requirements.txt

- https://github.com/pytorch/pytorch/issues/131662#issuecomment-2322909778
CUDA 12.1 & latest `torch` is problematic in Windows 11.
1.  Update default CUDA to 12.4

Update default version of the CUDA

---

app.py
modules/utils/cli_manager.py

- #275 
1. Refactor `bool` type in CLI to `str2bool()`. Done by : https://stackoverflow.com/a/18472142

Refactor bool to `str2bool` in CLI

---

modules/whisper/whisper_base.py

- #276 
- https://github.com/pytorch/pytorch/issues/87886
1. Use just `cpu` for `SparseMPS` device.

Handle `SparseMPS` device

---

modules/uvr/music_separator.py

1. Add path initialization to resolve path error when using custom output path

Initialize output paths for BGM separation

---

app.py
modules/whisper/whisper_base.py

1. Since `gradio` now supports new way to clean up the cache - https://www.gradio.app/guides/resource-cleanup#automatic-cache-cleanup-via-delete-cache
Remove deprecated functions and use `gradio`'s.

Update cache clean up logic

---

.gitignore
modules/whisper/faster_whisper_inference.py

- https://github.com/jhj0517/Whisper-WebUI/issues/309
- https://github.com/SYSTRAN/faster-whisper/issues/1030
1. Since `turbo` is not yet officially supported in `faster-whisper`, update `available_models()` to `faster-whisper`'s.

Update available models

---

app.py

- #335
1. In gradio 5 there is something different / buggy about the `file_types` attribute. So just remove it for now.
See the documentation  : https://www.gradio.app/docs/gradio/file

Remove file_types attribute

---

notebook/whisper-webui.ipynb

- #346 
- #347
1. Somehow colab isn't compatible with `ctranslate==4.5.0` (Regardless of `torch` version, tested with `torch >= 2.4.1`). So downgrade `ctranslate2` to 4.4.0.

Downgrade ctranslate2

---

tests/test_translation.py

- #351
1. Skip the test if DeepL API is unavailable

Skip test if DeepL API is unavailable

---

requirements.txt

- #356
1. https://github.com/hoveychen/gradio-i18n/pull/2 is merged and updated so use official package.

Update to gradio-i18n to official package

---

tests/test_config.py
tests/test_transcription.py

- #366
1. Test fails because `pytubefix` is detected as a bot in action, so skip it if it's detected as a bot.

Update pytube bot detection exception

---

app.py
configs/default_parameters.yaml
modules/whisper/base_transcription_pipeline.py

- https://github.com/jhj0517/Whisper-WebUI/pull/376#issuecomment-2453041265
Include loading of default value of file_format from config file.

Include loading of default value of file_format from config file.

---

configs/translation.yaml

- Translate interface text elements from English to French
- None
1. Add French translations for UI elements

feat(i18n): Add French translations for UI elements

---

modules/whisper/faster_whisper_inference.py

- https://github.com/jhj0517/Whisper-WebUI/issues/390#issuecomment-2491001511
1. Set `local_files_only` to True if the model path exists

Set conditional `local_files_only`

---

app.py
modules/whisper/faster_whisper_inference.py

- #406
1. Enable direct use of model from huggingface. 
Since the character `/` couldn't be used in the directory path, it's automatically updated to `--`.

Enable direct use of model from huggingface

---

Dockerfile

Currently `--no-cache-dir` is being used for Docker installation. This guarantees to install the latest version of the packages if some packages are problematic, but increases the installation time excessively. 
`-U` would guarantee to use the latest version of the packages and probably does the same thing.
1. Update from `--no-cache-dir` to `-U`

Fix dockerfile installation logic

---

.github/workflows/publish-docker.yml

- https://github.com/jhj0517/Whisper-WebUI/actions/runs/12005026101
Currently the disk is about 7GB~ when build finished. 
But it's saying that disk space is not enough, so clean the cache like other CI workflow.
1. Clean the cache to get more space in the action

Fix docker push with cleaning cache

---

modules/vad/silero_vad.py
modules/whisper/base_transcription_pipeline.py
notebook/whisper-webui.ipynb
requirements.txt

- #440
1. Use fixed version of `faster-whisper==1.1.1` and fix none type error
2. Update `faster-whisper` version in the colab notebook as well

Use fixed version of `faster-whisper==1.1.1`

---

modules/whisper/base_transcription_pipeline.py

- #456
1. When using VAD + Diarization together, the Diarization received the wrong `audio` input, which was processed by the VAD. 
So the pass the `origin_audio` to the Diarization pipeline.
2. Refactored error rasing

Fix wrong input for the diarization pipeline

---

app.py
configs/default_parameters.yaml
modules/whisper/base_transcription_pipeline.py
tests/test_transcription.py

- #466
1. Add ability to save outputs to the same directory as input file paths. If `save_same_dir` is True, it generates to both file paths to [/outputs](https://github.com/jhj0517/Whisper-WebUI/tree/master/outputs) and the same directory with inputs.
2. Set `add_timestamp` to false by default

Add ability to save output as same directory with inputs

---

modules/utils/audio_manager.py
modules/utils/subtitle_manager.py
modules/whisper/base_transcription_pipeline.py

- #468
1. Add audio file validation for some cases that the audio file is corrupted and can't be opened with `soundfile`. And right now it raises  error if the file is corrupted, so just leave a log message for corrupted audio instead of raising error.
This is example corrupted file that is not able to open with `soundfile`:
https://github.com/user-attachments/assets/adae2599-f372-457a-ac10-45f8646dfaea

Leave a message for corrupted audio instead of raising error

---

modules/whisper/base_transcription_pipeline.py

- when running Whisper-WebUI from docker, the cache folder for the huggingface diarization moddel is not a persistent folder. That means with every restart of the docker container, the hugging face token needs to be provided again via Gradio Webinterface so that the speaker diarization model can be downloaded again.
1. if the hugging face token is empty, then try to grab it from the environment variable "HF_TOKEN"
With this change it is possible to provide the HF token via environment variable to the docker container and does not have to be entered every time the docker container is restarted

add option to provide HuggingFace-token via environment variable

---

modules/whisper/base_transcription_pipeline.py

1. Fix total time elapsed does not account for all steps like UVR, copying original audio for speaker diarization, VAD,  restoring the timestamps after VAD
2. add some more progress messages to give the user a bit more information

Fix total time elapsed does not account for all steps

---

modules/utils/subtitle_manager.py

- # the file name length created from youtube videos is limited to 20 characters.
1. increase the length to 100 characters.

increase possible file name length for youtube transcriptions

---

modules/utils/audio_manager.py
modules/whisper/base_transcription_pipeline.py

- #479
1. Fix audio validation for video files

Fix audio validation with video file

---

modules/utils/subtitle_manager.py
modules/whisper/base_transcription_pipeline.py

- #
Validate segments not empty in subtitle_manager.py
1. 
Perform defensive checking to avoid the "list indices must be integers or slices, not str" exception caused by null values.
test file: https://github.com/anars/blank-audio/blob/master/10-minutes-of-silence.mp3

Validate segments

---

notebook/whisper-webui.ipynb

- #489 ( Colab notebook broken for `faster-whisper` )
1. Colab now uses CUDA 12.5 by default. So upgrade to `ctranlsate2==4.5.0` which is compatible.

Upgrade `ctranslate2` version in colab

---

modules/utils/audio_manager.py

- #492
1. Refactor audio validation with `faster_whisper.decode_audio()`. `decode_audio()` uses `av` to load audio not `soundfile`, `av` supports for more audio file extensions.

Refactor audio validation

---

backend/README.md
backend/configs/.env.example
backend/db/task/models.py
backend/routers/transcription/router.py
modules/whisper/base_transcription_pipeline.py
modules/whisper/faster_whisper_inference.py
modules/whisper/insanely_fast_whisper_inference.py
modules/whisper/whisper_Inference.py

- #506
1. Added progress callback in the transcription pipeline so users can track progress as numer in the backend
2. Added `.env.example`
3. **`progress: float` has been added to the table, the previous DB must be migrated.**

Add progress number tracking for `/transcription` endpoint

---

tests/test_bgm_separation.py
tests/test_diarization.py
tests/test_transcription.py
tests/test_vad.py

The test scripts currently import a test function from the `test_transcription` module.
**Simply importing this function unintentionally triggers the execution of `test_transcription`.**
So modularize the re-usable test function as `run_asr_pipeline()` without `@pytest` mark so let it re-usable without triggering the start of test in `test_transcription`
1. Modularized the shared test logic into `run_asr_pipeline()`, removing the `@pytest` decorator to prevent unintended execution during import.

Fix shared test module importing 

---

.github/workflows/publish-ghcr.yml

- #529
>[!NOTE]
> When using `GITHUB_TOKEN`, you need to explicitly write the correct permission for it. In this case `packages: write`
Doc link : https://docs.github.com/en/actions/security-for-github-actions/security-guides/automatic-token-authentication#permissions-for-the-github_token
1. Add `packages: write` permission in the workflow

Add write permission for `GITHUB_TOKEN` in the action

---

modules/uvr/music_separator.py

- #532
1. Handle when importing `uvr` package.
Note that the Windows 11 & `uvr` incompatibility needs to be investigated.
But it would take some time due to the limitations of my current setup.

Handle error when importing `uvr`

---

requirements.txt

- #546
1. Recent changes from `gradio-i18n` caused encoding errors when opening yaml. Not sure why.
Downgrading `gradio-i18n` fixes the bug.

Downgrade gradio-i18n to 0.3.0

---

README.md
requirements.txt

- https://github.com/jhj0517/Whisper-WebUI/issues/540#issuecomment-2852001024
`torch` does not support CUDA 12.4 binaries anymore. See:
https://pytorch.org/get-started/locally/
1. Upgrade minimum CUDA versions

Upgrade minimum CUDA version

---

modules/whisper/faster_whisper_inference.py

I've confirmed that enabling `word_timestamps` reduces hallucinations.
1. Set `word_timestamps` to True as it reduces hallucinations. However, word 'highlighting' in the subtitle only works when the "Word Timestamps" checkbox is enabled in the Web UI.
Even when I don't need the word highlighting feature in subtitles, I've confirmed that it reduces hallucinations, so it's now always set to True.

Set `word_timestamps` to always True
